name: las_dice
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pdal
  - python-pdal
  - geopandas
  - fiona
  - shapely
  - pyproj
  - gdal
  - click
  - tqdm
  - rich
  - pyyaml
  - pytest
